id: PEF2AD849
initial_creation_type: input
source_metadata:
  Title: Dhih Journal
  Editor: Samten, Ngawang & Pandey, Janardan
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2003'
  Samyaksambuddhabhāṣitaṃ pratimālakṣaṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:52:32.349804'
last_modified_at: '2022-03-08T16:52:32.349812'
